## Documentation for Dockerfiles: https://docs.docker.com/engine/reference/builder/

#Download a Linux Virtual Machine with Python installed
FROM python:2.7

#Suppress Python warnings
ENV PYTHONWARNINGS="ignore"

#Make a directory for our Python work files to go in
###
### your code here
###

# Switch to the work directory you just made
###
### your code here
###

# Install vim, a command-line text editor
RUN apt-get update
RUN apt-get -y install vim

#Install required Python dependencies from requirements.txt
###
### Copy lines of code from part 2 of the assignment here
###

#Runs an interactive Linux bash shell inside the terminal
CMD ["bash"]